user = "your_snowflake_user"
password = "your_snowflake_password"
account = "your_snowflake_account"
warehouse = "your_snowflake_warehouse"
database = "your_snowflake_database"
schema = "your_snowflake_schema"
role = "your_snowflake_role"
client_session_keep_alive = true

openai_api_key = "your_openai_api_key"
openai_model = "your_openai_model"